/* Contains Action Constants */

export const MAKE_REQUEST = 'COMMON/MAKE_REQUEST';
export const REQUEST_SUCCESS = 'COMMON/REQUEST_SUCCESS';
export const REQUEST_COMPLETED = 'COMMON/REQUEST_COMPLETED';
export const COUNT_FETCHED = 'COMMON/COUNT_FETCHED';
export const REQUEST_ERROR = 'COMMON/REQUEST_ERROR';
export const SECONDARY_VIEW = 'COMMON/SECONDARY_VIEW';
export const RESET = 'COMMON/RESET';
